### PR TITLE
Fixed the bug where `button_states()` returns None when `/AP` points to an indirect object.

### PR DESCRIPTION
**Pull request by airgalss**
Description: Some PDF widget objects may not have their `/AP`(Appearance Dictionary) directly pointing to a dictionary, which is enclosed with '<< >>', but rather pointing to an indirect object, expressed by an xref number in the format 'NNN 0 R'. Therefore, the current button_states() only can correctly handle cases where `/AP` points to a dictionary and cannot handle cases where it points to an indirect object. Consequently, I have introduced additional logic to handle the latter scenario, ensuring that `button_states()` can accurately return the on/off state names for button widgets even when `/AP` points to an indirect object.

Test: I have tested the modified `button_states()` function on the mentioned type of PDF, and it now correctly returns the states instead of None.

### CODE REVIEW

**Comment by airgalss** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by airgalss** [comment]
recheck

**Comment by JorjMcKie** [comment]
> recheck

There are lines in `def butten_states()` method that use tab characters instead of 4 spaces.
I would simply change that and copy the method's code to the same-named method in `src/__init__.py`.

**Comment by airgalss** [comment]
I have addressed the issue of mixing tabs and spaces, and copied it to `src/__init__.py`. I hope it should be fine now.

**Review by JorjMcKie — APPROVED** [review]

**Pull request merged**
