### PR TITLE
FIXES: #2961

### PR DESCRIPTION
**Pull request by bwagner**

### CODE REVIEW

**Comment by bwagner** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by JorjMcKie** [comment]
Possible arguments for loading a page are both, integers (page_number) and pairs `(chapter, page_number)`.

**Comment by julian-smith-artifex-com** [comment]
This change looks good, thanks.

But please rebase into a single commit, and exclude commit #0e2c07a0eff1ac "@bwagner has signed the CLA from Pull Request".

**Comment by julian-smith-artifex-com** [comment]
Oh, one other thing, could you describe what you're fixing explicitly, instead of just giving the Issue number? For example: "Improve handling of incorrect types passed to `Document.__get_item()`.

**Comment by bwagner** [comment]
Ah, sorry, need to rebase into single commit. Will try again!

**Comment by julian-smith-artifex-com** [comment]
Thanks for that, all looks good so merging now.

**Pull request merged**
