### PR TITLE
pipcl.py: allow providing python-config externally

### PR DESCRIPTION
**Pull request by rmelotte**
When cross-compiling (e.g. using Buildroot), the python-config executable that resides next to the host python executable provides incorrect includes (the ones for the host).

Since the correct path to python-config cannot be guessed, add an additional environment variable to allow setting the path to the correct python-config executable externally.

### CODE REVIEW

**Comment by rmelotte** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by julian-smith-artifex-com — COMMENTED** [review]
Many thanks for this.

If we are to make pipcl.py use an environment variable, i think it should be `PIPCL_PYTHON_CONFIG`, because `pipcl.py` is (or tries to be) a generic python backend.

[Alternatively, because PyMuPDF's `setup.py` uses various `PYMUPDF_*` environment variables, maybe we should add a new `python_config` arg to `pipcl.py:Package.__init__()`, and set it in `setup.py` from `PYMUPDF_PYTHON_CONFIG`? If you want to keep things simple for this PR though, please don't worry about doing this.]

**Comment by julian-smith-artifex-com** [comment]
[Oh and don't worry about the failure of test_quick - there's a known problem with mupdf master at the moment.]

**Comment by julian-smith-artifex-com** [comment]
BTW i've just rebased this PR's commits on top of recent changes that have fixed test_quick,m so that test_quick passes in the PR. You'll need to `git fetch` and do a hard reset to ensure your local branch matches the branch on GitHub.com. Apologies if this is inconvenient.

**Comment by rmelotte** [comment]
@julian-smith-artifex-com Thanks for your feedback!
To keep it simple for now, I've only renamed the variable to `PIPCL_PYTHON_CONFIG` and updated the documentation.

Thanks also for the rebase, I also forced-pushed it just now to keep it as a single commit.

**Comment by julian-smith-artifex-com** [comment]
Many thanks, i'll merge this now.

**Pull request merged**
