### PR TITLE
New Story abstractions and updated .github workflows and ISSUE_TEMPLATE.

### PR DESCRIPTION
**Pull request by julian-smith-artifex-com**

### CODE REVIEW

**Review by JorjMcKie — APPROVED** [review]

**Review by jamie-lemon — COMMENTED** [review]
I'm just looking at the story example stuff as the intricacies of the rest of it are beyond me.

For me what could be improved upon is the occurrence of "blah" in the output text. I would much rather see a more "real world" example or even "Lorum Ipsom", but just printing "blah" makes it feel cheaper if you know what I mean?

**Comment by julian-smith-artifex-com** [comment]
> I'm just looking at the story example stuff as the intricacies of the rest of it are beyond me.
> 
> For me what could be improved upon is the occurrence of "blah" in the output text. I would much rather see a more "real world" example or even "Lorum Ipsom", but just printing "blah" makes it feel cheaper if you know what I mean?

Agreed, cleaning up now.

**Comment by julian-smith-artifex-com** [comment]
See new commits, just 4 now, with hopefully better sample text etc.

**Review by jamie-lemon — APPROVED** [review]
All good

**Pull request merged**
