### PR TITLE
minor proofreading fixes

### PR DESCRIPTION
**Pull request by cbm755**
Few things I spotted while reading the docs.

I wasn't sure about "modifyable": to me it should be "modifiable" but perhaps it has some meaning to your ReST processor.  I didn't change it.

### CODE REVIEW

**Comment by jamie-lemon** [comment]
Thanks for this - do you mind redoing this and target the 1.21 branch for the merge? The latest version of the docs are on the 1.21 branch at the moment.

**Comment by cbm755** [comment]
Rebased, hope that worked.

**Comment by jamie-lemon** [comment]
Can you go ahead and change the instance of "modifyable" to "modifiable" and squash your commits into a single commit? So just one commit called "Documentation: Typo fixes". Then I think we are good!

**Comment by cbm755** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by cbm755** [comment]
recheck

**Comment by jamie-lemon** [comment]
recheck

**Comment by jamie-lemon** [comment]
Look good to me - lots of typos fixed - much appreciated 👍

**Pull request merged**
