### PR TITLE
typo het_toc instead of get_toc

### PR DESCRIPTION
**Pull request by JoKalliauer**
Update recipes-common-issues-and-their-solutions.rst

typo "doc.het_toc()" instead of "doc.get_toc()"

### CODE REVIEW

**Comment by JoKalliauer** [comment]
- [x] I have read the CLA Document and I hereby sign the CLA

[Artifex Contributor License Agreement_signed.pdf](https://github.com/pymupdf/PyMuPDF/files/14639832/Artifex.Contributor.License.Agreement_signed.pdf)

**Comment by JoKalliauer** [comment]
recheck

**Comment by julian-smith-artifex-com** [comment]
[Please ignore the failing `Test quick`; it is because of a new version of libclang on pypi that mupdf does not build with. I have a fix in my tree.]

**Comment by JoKalliauer** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by julian-smith-artifex-com** [comment]
Thanks, it looks fine, i'll merge.

**Pull request merged**
