### PR TITLE
Fix for FreeBSD

### PR DESCRIPTION
**Pull request by dsh2dsh**
Without this change I'm getting an exception trying to do
```
>>> import fitz
```

### CODE REVIEW

**Comment by jamie-lemon** [comment]
Please try again with the latest release!

**Comment by dsh2dsh** [comment]
But what did change? It still doesn't add "freetype" and "harfbuzz" into libraries.

**Comment by julian-smith-artifex-com** [comment]
Thanks for this suggested change. Unfortunately i don't have access to a freebsd machine so am unable to test it.

The PR doesn't seem to have a commit that patches the current master, so it's a little tricky to see exactly what's going on. Could you rebase your branch on top of the latest master?

I think it might be good to make your change only apply when building on freebsd. So maybe a patch like this would work?:
```
index c283885..e36cb6b 100644
--- a/setup.py
+++ b/setup.py
@@ -607,6 +607,12 @@ if ('-h' not in sys.argv and '--help' not in sys.argv
         include_dirs.append("/opt/homebrew/include/freetype2")
 
         library_dirs.append("/opt/homebrew/lib")
+        
+        if sys.platform.startswith( 'freebsd'):
+            libraries += [
+                    'freetype',
+                    'harfbuzz',
+                    ]
 
     else:
         # Windows.
```

**Comment by dsh2dsh** [comment]
@julian-smith-artifex-com  your diff shows exactly what my change is doing.

**Comment by julian-smith-artifex-com** [comment]
Ok, in that case, could you try applying my diff to current master (removing your changes and merges), and verify that it works on your freebsd machine?

If all is ok, i'll apply my patch to the tree.

[This will avoid the need for a signed contributor license agreement in this case.]

**Comment by julian-smith-artifex-com** [comment]
> @julian-smith-artifex-com would you like me to close my PR in favor of yours?

Ah, sorry, our postings crossed. Yes, that sounds like the simplest way forward. If you could verify it works, that would be a bonus.

**Comment by julian-smith-artifex-com** [comment]
I'll mention you in the commit message.

BTW if you prefer, i'd be happy to merge a pull request with you signing a contributor license agreement.

**Comment by dsh2dsh** [comment]
@julian-smith-artifex-com thank you, I don't think we need to complicate it by the agreement. I'll test the build and let you know.

**Comment by dsh2dsh** [comment]
OK, I've tested fresh master and system installed mupdf 1.20.0. Without the change I'm getting
```
❯ python
Python 3.8.13 (default, May 10 2022, 01:15:55) 
[Clang 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c on freebsd13
Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/www/pyx-py-env/lib/python3.8/site-packages/PyMuPDF-1.20.0-py3.8-freebsd-13.1-RELEASE-amd64.egg/fitz/__init__.py", line 10, in <module>
    from fitz.fitz import *
  File "/usr/local/www/pyx-py-env/lib/python3.8/site-packages/PyMuPDF-1.20.0-py3.8-freebsd-13.1-RELEASE-amd64.egg/fitz/fitz.py", line 17, in <module>
    from . import _fitz
ImportError: /usr/local/www/pyx-py-env/lib/python3.8/site-packages/PyMuPDF-1.20.0-py3.8-freebsd-13.1-RELEASE-amd64.egg/fitz/_fitz.cpython-38.so: Undefined symbol "FT_Get_First_Char"
```

With this change
```
diff --git a/setup.py b/setup.py
index c283885..a745943 100644
--- a/setup.py
+++ b/setup.py
@@ -608,6 +608,12 @@ if ('-h' not in sys.argv and '--help' not in sys.argv
 
         library_dirs.append("/opt/homebrew/lib")
 
+        if sys.platform.startswith( 'freebsd'):
+            libraries += [
+                    'freetype',
+                    'harfbuzz',
+                    ]
+
     else:
         # Windows.
         assert mupdf_local
```
it works fine
```
❯ python
Python 3.8.13 (default, May 10 2022, 01:15:55) 
[Clang 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c on freebsd13
Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
>>>
```

**Comment by julian-smith-artifex-com** [comment]
Great, thanks for testing. I'll push the fix to master soon.

**Pull request closed without merging**
