### PR TITLE
Add script_focus and script_blur options to widget

### PR DESCRIPTION
**Pull request by m42e**
Add possibility to read and write the script_focus and script_blur. 
This allows setting the action triggered on focus and blur.

Depends-On: https://github.com/ArtifexSoftware/mupdf/pull/37

### CODE REVIEW

**Comment by m42e** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by m42e** [comment]
recheck

**Comment by m42e** [comment]
recheck

**Review by JorjMcKie — APPROVED** [review]

**Comment by jamie-lemon** [comment]
recheck

**Review by JorjMcKie — APPROVED** [review]

**Review by JorjMcKie — APPROVED** [review]

**Pull request merged**
