### PR TITLE
Julian 1.20.1

### PR DESCRIPTION
**Pull request by julian-smith-artifex-com**
Proposed changes for a 1.20.1 release.

I think these changes have already been checked, except for:
* Fixed some sphinx warnings/errors in .rst files.
* Update changelogs, version strings and release date for release of 1.20.1.

@JorjMcKie and @jamie-lemon, if you have time, please take a quick look. Thanks.

### CODE REVIEW

**Review by JorjMcKie — APPROVED** [review]
I looked at all changed files.
Everything looks good to me.

**Comment by JorjMcKie** [comment]
Hi Julian,
I have a fix for #1645. This pertains to lines 52 and 54 in helper-annot.i:
Instead of:

grafik

They should be:

grafik

I think it would make sense for such a trivial change to be included in this patch version ...
I tested it on my machine. There are nor side effects to other parts.

**Comment by julian-smith-artifex-com** [comment]
> Hi Julian, I have a fix for #1645. This pertains to lines 52 and 54 in helper-annot.i: Instead of:

Thanks for this, i've pushed your fix (including a test) to my 1.20.1 branch.

**Comment by JorjMcKie** [comment]
Thanks a lot, Julian.

**Review by jamie-lemon — APPROVED** [review]
LGTM

**Pull request merged**
