### PR TITLE
fix getMetadata memory leak

### PR DESCRIPTION
**Pull request by zhou3968322**
value not released, caused memory leak.

### CODE REVIEW

**Review by JorjMcKie — APPROVED** [review]
Thanks for catching this!

**Comment by JorjMcKie** [comment]
Thank you!

**Comment by zhou3968322** [comment]
any plan to deploy a new version of pyMuPDF




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jorj X. McKie"<notifications@github.com&gt;; 
发送时间: 2020年11月11日(星期三) 晚上7:36
收件人: "pymupdf/PyMuPDF"<PyMuPDF@noreply.github.com&gt;; 
抄送: "磐石"<zhou3968322@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pymupdf/PyMuPDF] fix getMetadata memory leak (#720)





 
Thank you!

**Comment by JorjMcKie** [comment]
I hope I can make it later during this week. There pre-release v1.18.4 wheels in repo https://github.com/pymupdf/PyMuPDF-wheels. Look at branches `linux` or `osx`.
If you want a Windows version drop me a note.

**Comment by zhou3968322** [comment]
thank you.



发自我的iPhone


------------------ Original ------------------

**Pull request merged**
